DROP TABLE IF EXISTS forum_users CASCADE;

CREATE TABLE IF NOT EXISTS forum_users (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  forum_id INTEGER REFERENCES forums(id) ON DELETE CASCADE NOT NULL
);