DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Forums CASCADE;
DROP TABLE IF EXISTS Threads CASCADE;

CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS Users (
  id SERIAL PRIMARY KEY,
  about TEXT DEFAULT NULL,
  fullname TEXT DEFAULT NULL,
  nickname CITEXT  UNIQUE ,
  email CITEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS Forums (
  id SERIAL PRIMARY KEY,
  posts INTEGER DEFAULT 0,
  threads INTEGER DEFAULT 0,
  title TEXT,
  slug CITEXT UNIQUE NOT NULL,
  user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS Threads (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE NOT NULL,
  created TIMESTAMPTZ DEFAULT NOW(),
  forum_id INTEGER REFERENCES Forums(id) ON DELETE CASCADE NOT NULL,
  message TEXT,
  slug CITEXT UNIQUE ,
  title TEXT,
  votes INTEGER DEFAULT 0
);